version: '3.8'

services:
  backend:
    build: ./todoproject
    container_name: todoproject_backend
    ports:
      - "8000:8000"
    volumes:
      - ./todoproject:/app
    environment:
      - DEBUG=True
