name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the backend Docker image
    - name: Build backend Docker image
      run: |
        docker build -t fullstack-backend:latest -f todoproject/Dockerfile .

    # Step 4: Log in to Docker Hub using Secrets
    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # Step 5: Tag the Docker image
    - name: Tag backend Docker image
      run: |
        docker tag fullstack-backend:latest fforhad/fullstack-backend:latest

    # Step 6: Push the Docker image to Docker Hub
    - name: Push backend Docker image to Docker Hub
      run: |
        docker push fforhad/fullstack-backend:latest

    # Step 7: Deploy to server using SSH (with username and password)
    - name: Deploy to server using SSH password
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@192.168.0.7 'docker pull fforhad/fullstack-backend:latest && docker stop fullstack-backend || true && docker rm fullstack-backend || true && docker run -d --name fullstack-backend -p 8000:8000 fforhad/fullstack-backend:latest'
